inherit_from:
  - https://github.com/jgarber623/rubocop-configs/raw/main/.rubocop.yml
  - https://github.com/jgarber623/rubocop-configs/raw/main/.rubocop-rspec.yml

require:
  - rubocop-packaging

# Checks that the keys, separators, and values of a multi-line hash literal are
# aligned according to configuration.
Layout/HashAlignment:
  EnforcedHashRocketStyle: table

# Makes sure that Ruby source files have snake_case names.
Naming/FileName:
  Exclude:
    - lib/nokogiri/html-ext.rb
